// Package store is the SQLite-backed control-plane store: the durable record
// of Beamhalls, beams, builds, releases, routes, resources, secrets metadata,
// the audit log, and the scheduler's armed pause deadlines. It is the
// appliance's own state — deployed beams still get real Postgres (docs/PLAN.md
// §4).
//
// Storage decisions (also documented in migrations/0001_init.sql):
//
//   - modernc.org/sqlite (pure Go, CGO-free) in WAL mode, with a single
//     connection (MaxOpenConns(1)): control-plane traffic is tiny, and one
//     writer removes the whole SQLITE_BUSY class of failure.
//   - Timestamps are stored as UTC unix nanoseconds (0 = unset), durations as
//     nanoseconds, nested domain structs as JSON TEXT columns. This keeps the
//     schema driver-agnostic and round-trips time.Time exactly.
//   - ULIDs (crypto/rand entropy) for IDs; the empty string is "unset" for
//     pointer columns.
//   - Query code is generated by sqlc into internal/store/db (see sqlc.yaml);
//     this package wraps it in domain types and owns transactions.
package store

import (
	"context"
	"crypto/rand"
	"database/sql"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/oklog/ulid/v2"
	sqlite "modernc.org/sqlite"

	"github.com/Beamhall/beamhall/internal/domain"
	"github.com/Beamhall/beamhall/internal/store/db"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

var (
	// ErrNotFound is returned when a Get hits no row.
	ErrNotFound = errors.New("store: not found")
	// ErrConflict is returned when an insert/update violates a uniqueness
	// constraint (duplicate slug, membership, hostname, secret key, ...).
	ErrConflict = errors.New("store: conflict")
	// ErrQuota is returned when a transactional quota gate (live slots) is
	// exhausted.
	ErrQuota = errors.New("store: quota exceeded")
)

// Store is the control-plane store. Safe for concurrent use.
type Store struct {
	sqldb *sql.DB
	q     *db.Queries
	now   func() time.Time
}

// Option configures a Store.
type Option func(*Store)

// WithNow overrides the clock (for tests).
func WithNow(now func() time.Time) Option { return func(s *Store) { s.now = now } }

// Open opens (creating if needed) the SQLite database at path and applies any
// pending migrations. The parent directory must exist.
func Open(ctx context.Context, path string, opts ...Option) (*Store, error) {
	dsn := "file:" + path + "?" + strings.Join([]string{
		"_pragma=busy_timeout(5000)",
		"_pragma=journal_mode(WAL)",
		"_pragma=foreign_keys(1)",
		"_pragma=synchronous(NORMAL)",
		"_txlock=immediate",
	}, "&")
	sqldb, err := sql.Open("sqlite", dsn)
	if err != nil {
		return nil, fmt.Errorf("open sqlite %s: %w", path, err)
	}
	// Single connection: one writer, no SQLITE_BUSY; see package doc.
	sqldb.SetMaxOpenConns(1)
	if err := migrate(ctx, sqldb); err != nil {
		sqldb.Close()
		return nil, fmt.Errorf("migrate %s: %w", path, err)
	}
	s := &Store{sqldb: sqldb, q: db.New(sqldb), now: time.Now}
	for _, o := range opts {
		o(s)
	}
	return s, nil
}

// Close closes the underlying database.
func (s *Store) Close() error { return s.sqldb.Close() }

// Snapshot writes a consistent, fully-checkpointed copy of the database to
// destPath using SQLite's VACUUM INTO. It runs online (a read transaction, no
// long writer lock) so a live appliance can be backed up. destPath must not
// already exist. The copy is a plain single file with no WAL sidecar — safe to
// archive and restore by itself.
func (s *Store) Snapshot(ctx context.Context, destPath string) error {
	if _, err := os.Stat(destPath); err == nil {
		return fmt.Errorf("snapshot destination %s already exists", destPath)
	}
	// VACUUM INTO takes a string literal, not a bind parameter; the path is
	// operator-supplied (a backup target), and single quotes are escaped.
	q := "VACUUM INTO '" + strings.ReplaceAll(destPath, "'", "''") + "'"
	if _, err := s.sqldb.ExecContext(ctx, q); err != nil {
		return fmt.Errorf("snapshot to %s: %w", destPath, err)
	}
	return nil
}

// migrate applies embedded migrations newer than PRAGMA user_version, each in
// its own transaction. Files must be named NNNN_label.sql with NNNN dense and
// ascending from 0001; user_version tracks the last applied NNNN.
func migrate(ctx context.Context, sqldb *sql.DB) error {
	names, err := fs.Glob(migrationsFS, "migrations/*.sql")
	if err != nil {
		return err
	}
	sort.Strings(names)

	var current int
	if err := sqldb.QueryRowContext(ctx, "PRAGMA user_version").Scan(&current); err != nil {
		return fmt.Errorf("read user_version: %w", err)
	}

	for i, name := range names {
		v := i + 1
		if want := fmt.Sprintf("migrations/%04d_", v); !strings.HasPrefix(name, want) {
			return fmt.Errorf("migration %q out of sequence (want prefix %q)", name, want)
		}
		if v <= current {
			continue
		}
		text, err := fs.ReadFile(migrationsFS, name)
		if err != nil {
			return err
		}
		tx, err := sqldb.BeginTx(ctx, nil)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, string(text)); err != nil {
			tx.Rollback()
			return fmt.Errorf("apply %s: %w", name, err)
		}
		// PRAGMA user_version is written to the DB header and is transactional.
		if _, err := tx.ExecContext(ctx, fmt.Sprintf("PRAGMA user_version = %d", v)); err != nil {
			tx.Rollback()
			return fmt.Errorf("set user_version %d: %w", v, err)
		}
		if err := tx.Commit(); err != nil {
			return fmt.Errorf("commit %s: %w", name, err)
		}
	}
	return nil
}

// NewID returns a fresh ULID: sortable by creation time, crypto/rand entropy.
func NewID() domain.ID {
	return domain.ID(ulid.MustNew(ulid.Now(), rand.Reader).String())
}

// withTx runs fn inside a single transaction (BEGIN IMMEDIATE per the DSN).
func (s *Store) withTx(ctx context.Context, fn func(q *db.Queries) error) error {
	tx, err := s.sqldb.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	if err := fn(s.q.WithTx(tx)); err != nil {
		tx.Rollback()
		return err
	}
	return tx.Commit()
}

// mapErr translates driver errors into the store's sentinel errors.
func mapErr(err error) error {
	if err == nil {
		return nil
	}
	if errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("%w: %w", ErrNotFound, err)
	}
	var se *sqlite.Error
	const sqliteConstraint = 19 // SQLITE_CONSTRAINT (low byte of extended codes)
	if errors.As(err, &se) && se.Code()&0xff == sqliteConstraint {
		return fmt.Errorf("%w: %w", ErrConflict, err)
	}
	return err
}

// affected adapts an :execrows result (rows-affected, err) for mutations that
// target a single row by id. A zero count means the id did not exist, which is
// reported as ErrNotFound so a typoed/stale id surfaces instead of silently
// succeeding as a no-op. Driver errors are mapped as usual.
func affected(n int64, err error) error {
	if err != nil {
		return mapErr(err)
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

// ns converts a time to stored unix nanoseconds; the zero time maps to 0.
func ns(t time.Time) int64 {
	if t.IsZero() {
		return 0
	}
	return t.UnixNano()
}

// fromNS is the inverse of ns.
func fromNS(n int64) time.Time {
	if n == 0 {
		return time.Time{}
	}
	return time.Unix(0, n).UTC()
}

func encJSON(v any) (string, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func decJSON[T any](s string, dst *T) error {
	return json.Unmarshal([]byte(s), dst)
}
