// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_requests.sql

package db

import (
	"context"
)

const decideAdminActionRequest = `-- name: DecideAdminActionRequest :execrows
UPDATE admin_action_requests
SET status = ?, reason = ?, result = ?, decided_by = ?, decided_at = ?
WHERE id = ? AND status = 'pending'
`

type DecideAdminActionRequestParams struct {
	Status    string
	Reason    string
	Result    string
	DecidedBy string
	DecidedAt int64
	ID        string
}

func (q *Queries) DecideAdminActionRequest(ctx context.Context, arg DecideAdminActionRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decideAdminActionRequest,
		arg.Status,
		arg.Reason,
		arg.Result,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAdminActionRequest = `-- name: GetAdminActionRequest :one
SELECT id, action_type, summary, payload_cipher, requested_by, status, reason, result, created_at, decided_by, decided_at FROM admin_action_requests WHERE id = ?
`

func (q *Queries) GetAdminActionRequest(ctx context.Context, id string) (AdminActionRequest, error) {
	row := q.db.QueryRowContext(ctx, getAdminActionRequest, id)
	var i AdminActionRequest
	err := row.Scan(
		&i.ID,
		&i.ActionType,
		&i.Summary,
		&i.PayloadCipher,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.Result,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const insertAdminActionRequest = `-- name: InsertAdminActionRequest :exec
INSERT INTO admin_action_requests (id, action_type, summary, payload_cipher, requested_by, status, created_at)
VALUES (?, ?, ?, ?, ?, 'pending', ?)
`

type InsertAdminActionRequestParams struct {
	ID            string
	ActionType    string
	Summary       string
	PayloadCipher []byte
	RequestedBy   string
	CreatedAt     int64
}

func (q *Queries) InsertAdminActionRequest(ctx context.Context, arg InsertAdminActionRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertAdminActionRequest,
		arg.ID,
		arg.ActionType,
		arg.Summary,
		arg.PayloadCipher,
		arg.RequestedBy,
		arg.CreatedAt,
	)
	return err
}

const listPendingAdminActionRequests = `-- name: ListPendingAdminActionRequests :many
SELECT id, action_type, summary, payload_cipher, requested_by, status, reason, result, created_at, decided_by, decided_at FROM admin_action_requests WHERE status = 'pending' ORDER BY created_at
`

func (q *Queries) ListPendingAdminActionRequests(ctx context.Context) ([]AdminActionRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAdminActionRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminActionRequest
	for rows.Next() {
		var i AdminActionRequest
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.Summary,
			&i.PayloadCipher,
			&i.RequestedBy,
			&i.Status,
			&i.Reason,
			&i.Result,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
