// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const appendAuditEvent = `-- name: AppendAuditEvent :one
INSERT INTO audit_events (
    id, at, actor_id, actor_token_jti, beamhall_id, beam_id, action, decision,
    reason, request_digest, result_status, source_ip, prev_hash, hash
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING seq
`

type AppendAuditEventParams struct {
	ID            string
	At            int64
	ActorID       string
	ActorTokenJti string
	BeamhallID    string
	BeamID        string
	Action        string
	Decision      string
	Reason        string
	RequestDigest string
	ResultStatus  string
	SourceIp      string
	PrevHash      string
	Hash          string
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendAuditEvent,
		arg.ID,
		arg.At,
		arg.ActorID,
		arg.ActorTokenJti,
		arg.BeamhallID,
		arg.BeamID,
		arg.Action,
		arg.Decision,
		arg.Reason,
		arg.RequestDigest,
		arg.ResultStatus,
		arg.SourceIp,
		arg.PrevHash,
		arg.Hash,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const auditCutSeqByAge = `-- name: AuditCutSeqByAge :one
SELECT COALESCE(MAX(seq), 0) FROM audit_events WHERE at < ?
`

// The newest event strictly older than the cutoff: the prune-through point for
// an age-based retention policy (0 when nothing is that old).
func (q *Queries) AuditCutSeqByAge(ctx context.Context, at int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, auditCutSeqByAge, at)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const auditHashBySeq = `-- name: AuditHashBySeq :one
SELECT hash FROM audit_events WHERE seq = ?
`

func (q *Queries) AuditHashBySeq(ctx context.Context, seq int64) (string, error) {
	row := q.db.QueryRowContext(ctx, auditHashBySeq, seq)
	var hash string
	err := row.Scan(&hash)
	return hash, err
}

const deleteAuditEventsThrough = `-- name: DeleteAuditEventsThrough :execrows
DELETE FROM audit_events WHERE seq <= ?
`

func (q *Queries) DeleteAuditEventsThrough(ctx context.Context, seq int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditEventsThrough, seq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertAuditCheckpoint = `-- name: InsertAuditCheckpoint :exec
INSERT INTO audit_checkpoints (through_seq, anchor_hash, pruned_count, at, pruned_by)
VALUES (?, ?, ?, ?, ?)
`

type InsertAuditCheckpointParams struct {
	ThroughSeq  int64
	AnchorHash  string
	PrunedCount int64
	At          int64
	PrunedBy    string
}

func (q *Queries) InsertAuditCheckpoint(ctx context.Context, arg InsertAuditCheckpointParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditCheckpoint,
		arg.ThroughSeq,
		arg.AnchorHash,
		arg.PrunedCount,
		arg.At,
		arg.PrunedBy,
	)
	return err
}

const lastAuditEvent = `-- name: LastAuditEvent :one
SELECT seq, id, at, actor_id, actor_token_jti, beamhall_id, beam_id, "action", decision, reason, request_digest, result_status, source_ip, prev_hash, hash FROM audit_events ORDER BY seq DESC LIMIT 1
`

func (q *Queries) LastAuditEvent(ctx context.Context) (AuditEvent, error) {
	row := q.db.QueryRowContext(ctx, lastAuditEvent)
	var i AuditEvent
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.At,
		&i.ActorID,
		&i.ActorTokenJti,
		&i.BeamhallID,
		&i.BeamID,
		&i.Action,
		&i.Decision,
		&i.Reason,
		&i.RequestDigest,
		&i.ResultStatus,
		&i.SourceIp,
		&i.PrevHash,
		&i.Hash,
	)
	return i, err
}

const latestAuditCheckpoint = `-- name: LatestAuditCheckpoint :one
SELECT through_seq, anchor_hash, pruned_count, at, pruned_by
FROM audit_checkpoints ORDER BY through_seq DESC LIMIT 1
`

type LatestAuditCheckpointRow struct {
	ThroughSeq  int64
	AnchorHash  string
	PrunedCount int64
	At          int64
	PrunedBy    string
}

func (q *Queries) LatestAuditCheckpoint(ctx context.Context) (LatestAuditCheckpointRow, error) {
	row := q.db.QueryRowContext(ctx, latestAuditCheckpoint)
	var i LatestAuditCheckpointRow
	err := row.Scan(
		&i.ThroughSeq,
		&i.AnchorHash,
		&i.PrunedCount,
		&i.At,
		&i.PrunedBy,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT seq, id, at, actor_id, actor_token_jti, beamhall_id, beam_id, "action", decision, reason, request_digest, result_status, source_ip, prev_hash, hash FROM audit_events WHERE seq > ? ORDER BY seq LIMIT ?
`

type ListAuditEventsParams struct {
	Seq   int64
	Limit int64
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.At,
			&i.ActorID,
			&i.ActorTokenJti,
			&i.BeamhallID,
			&i.BeamID,
			&i.Action,
			&i.Decision,
			&i.Reason,
			&i.RequestDigest,
			&i.ResultStatus,
			&i.SourceIp,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByBeamhall = `-- name: ListAuditEventsByBeamhall :many
SELECT seq, id, at, actor_id, actor_token_jti, beamhall_id, beam_id, "action", decision, reason, request_digest, result_status, source_ip, prev_hash, hash FROM audit_events WHERE beamhall_id = ? AND seq > ? ORDER BY seq LIMIT ?
`

type ListAuditEventsByBeamhallParams struct {
	BeamhallID string
	Seq        int64
	Limit      int64
}

func (q *Queries) ListAuditEventsByBeamhall(ctx context.Context, arg ListAuditEventsByBeamhallParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEventsByBeamhall, arg.BeamhallID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.At,
			&i.ActorID,
			&i.ActorTokenJti,
			&i.BeamhallID,
			&i.BeamID,
			&i.Action,
			&i.Decision,
			&i.Reason,
			&i.RequestDigest,
			&i.ResultStatus,
			&i.SourceIp,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxAuditSeq = `-- name: MaxAuditSeq :one
SELECT COALESCE(MAX(seq), 0) FROM audit_events
`

func (q *Queries) MaxAuditSeq(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxAuditSeq)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}
