// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beamhalls.sql

package db

import (
	"context"
)

const getBeamhall = `-- name: GetBeamhall :one
SELECT id, slug, display_name, department, status, security_context_id, network_policy_json, quota_json, live_slot_limit, created_by, created_at, updated_at FROM beamhalls WHERE id = ?
`

func (q *Queries) GetBeamhall(ctx context.Context, id string) (Beamhall, error) {
	row := q.db.QueryRowContext(ctx, getBeamhall, id)
	var i Beamhall
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Department,
		&i.Status,
		&i.SecurityContextID,
		&i.NetworkPolicyJson,
		&i.QuotaJson,
		&i.LiveSlotLimit,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBeamhallBySlug = `-- name: GetBeamhallBySlug :one
SELECT id, slug, display_name, department, status, security_context_id, network_policy_json, quota_json, live_slot_limit, created_by, created_at, updated_at FROM beamhalls WHERE slug = ?
`

func (q *Queries) GetBeamhallBySlug(ctx context.Context, slug string) (Beamhall, error) {
	row := q.db.QueryRowContext(ctx, getBeamhallBySlug, slug)
	var i Beamhall
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Department,
		&i.Status,
		&i.SecurityContextID,
		&i.NetworkPolicyJson,
		&i.QuotaJson,
		&i.LiveSlotLimit,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecurityContextByBeamhall = `-- name: GetSecurityContextByBeamhall :one
SELECT id, beamhall_id, runtime_class, userns_remap, cap_drop_json, cap_add_json, seccomp_profile, apparmor_profile, no_new_privileges, read_only_rootfs, tmpfs_json, cgroup_limits_json, template FROM security_contexts WHERE beamhall_id = ?
`

func (q *Queries) GetSecurityContextByBeamhall(ctx context.Context, beamhallID string) (SecurityContext, error) {
	row := q.db.QueryRowContext(ctx, getSecurityContextByBeamhall, beamhallID)
	var i SecurityContext
	err := row.Scan(
		&i.ID,
		&i.BeamhallID,
		&i.RuntimeClass,
		&i.UsernsRemap,
		&i.CapDropJson,
		&i.CapAddJson,
		&i.SeccompProfile,
		&i.ApparmorProfile,
		&i.NoNewPrivileges,
		&i.ReadOnlyRootfs,
		&i.TmpfsJson,
		&i.CgroupLimitsJson,
		&i.Template,
	)
	return i, err
}

const insertBeamhall = `-- name: InsertBeamhall :exec
INSERT INTO beamhalls (
    id, slug, display_name, department, status, security_context_id,
    network_policy_json, quota_json, live_slot_limit, created_by, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBeamhallParams struct {
	ID                string
	Slug              string
	DisplayName       string
	Department        string
	Status            string
	SecurityContextID string
	NetworkPolicyJson string
	QuotaJson         string
	LiveSlotLimit     int64
	CreatedBy         string
	CreatedAt         int64
	UpdatedAt         int64
}

func (q *Queries) InsertBeamhall(ctx context.Context, arg InsertBeamhallParams) error {
	_, err := q.db.ExecContext(ctx, insertBeamhall,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.Department,
		arg.Status,
		arg.SecurityContextID,
		arg.NetworkPolicyJson,
		arg.QuotaJson,
		arg.LiveSlotLimit,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSecurityContext = `-- name: InsertSecurityContext :exec
INSERT INTO security_contexts (
    id, beamhall_id, runtime_class, userns_remap, cap_drop_json, cap_add_json,
    seccomp_profile, apparmor_profile, no_new_privileges, read_only_rootfs,
    tmpfs_json, cgroup_limits_json, template
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSecurityContextParams struct {
	ID               string
	BeamhallID       string
	RuntimeClass     string
	UsernsRemap      bool
	CapDropJson      string
	CapAddJson       string
	SeccompProfile   string
	ApparmorProfile  string
	NoNewPrivileges  bool
	ReadOnlyRootfs   bool
	TmpfsJson        string
	CgroupLimitsJson string
	Template         string
}

func (q *Queries) InsertSecurityContext(ctx context.Context, arg InsertSecurityContextParams) error {
	_, err := q.db.ExecContext(ctx, insertSecurityContext,
		arg.ID,
		arg.BeamhallID,
		arg.RuntimeClass,
		arg.UsernsRemap,
		arg.CapDropJson,
		arg.CapAddJson,
		arg.SeccompProfile,
		arg.ApparmorProfile,
		arg.NoNewPrivileges,
		arg.ReadOnlyRootfs,
		arg.TmpfsJson,
		arg.CgroupLimitsJson,
		arg.Template,
	)
	return err
}

const listBeamhalls = `-- name: ListBeamhalls :many
SELECT id, slug, display_name, department, status, security_context_id, network_policy_json, quota_json, live_slot_limit, created_by, created_at, updated_at FROM beamhalls ORDER BY slug
`

func (q *Queries) ListBeamhalls(ctx context.Context) ([]Beamhall, error) {
	rows, err := q.db.QueryContext(ctx, listBeamhalls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Beamhall
	for rows.Next() {
		var i Beamhall
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Department,
			&i.Status,
			&i.SecurityContextID,
			&i.NetworkPolicyJson,
			&i.QuotaJson,
			&i.LiveSlotLimit,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBeamhall = `-- name: UpdateBeamhall :execrows
UPDATE beamhalls SET
    display_name = ?, department = ?, status = ?, network_policy_json = ?,
    quota_json = ?, live_slot_limit = ?, updated_at = ?
WHERE id = ?
`

type UpdateBeamhallParams struct {
	DisplayName       string
	Department        string
	Status            string
	NetworkPolicyJson string
	QuotaJson         string
	LiveSlotLimit     int64
	UpdatedAt         int64
	ID                string
}

func (q *Queries) UpdateBeamhall(ctx context.Context, arg UpdateBeamhallParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBeamhall,
		arg.DisplayName,
		arg.Department,
		arg.Status,
		arg.NetworkPolicyJson,
		arg.QuotaJson,
		arg.LiveSlotLimit,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSecurityContext = `-- name: UpdateSecurityContext :execrows
UPDATE security_contexts SET
    runtime_class = ?, userns_remap = ?, cap_drop_json = ?, cap_add_json = ?,
    seccomp_profile = ?, apparmor_profile = ?, no_new_privileges = ?,
    read_only_rootfs = ?, tmpfs_json = ?, cgroup_limits_json = ?, template = ?
WHERE id = ?
`

type UpdateSecurityContextParams struct {
	RuntimeClass     string
	UsernsRemap      bool
	CapDropJson      string
	CapAddJson       string
	SeccompProfile   string
	ApparmorProfile  string
	NoNewPrivileges  bool
	ReadOnlyRootfs   bool
	TmpfsJson        string
	CgroupLimitsJson string
	Template         string
	ID               string
}

func (q *Queries) UpdateSecurityContext(ctx context.Context, arg UpdateSecurityContextParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSecurityContext,
		arg.RuntimeClass,
		arg.UsernsRemap,
		arg.CapDropJson,
		arg.CapAddJson,
		arg.SeccompProfile,
		arg.ApparmorProfile,
		arg.NoNewPrivileges,
		arg.ReadOnlyRootfs,
		arg.TmpfsJson,
		arg.CgroupLimitsJson,
		arg.Template,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
