// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beams.sql

package db

import (
	"context"
)

const countBeamsByBeamhall = `-- name: CountBeamsByBeamhall :one
SELECT COUNT(*) FROM beams WHERE beamhall_id = ? AND status = 'active'
`

func (q *Queries) CountBeamsByBeamhall(ctx context.Context, beamhallID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBeamsByBeamhall, beamhallID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLiveBeamsByBeamhall = `-- name: CountLiveBeamsByBeamhall :one
SELECT COUNT(*) FROM beams WHERE beamhall_id = ? AND mode = 'live' AND status = 'active'
`

func (q *Queries) CountLiveBeamsByBeamhall(ctx context.Context, beamhallID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveBeamsByBeamhall, beamhallID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBeam = `-- name: GetBeam :one
SELECT id, beamhall_id, slug, display_name, runtime_hint, mode, state, current_release_id, desired_release_id, security_template, preview_pause_after, resumed_at, git_remote_url, repo_id, created_by, created_at, updated_at, status, preview_host, live_release_id, live_state FROM beams WHERE id = ?
`

func (q *Queries) GetBeam(ctx context.Context, id string) (Beam, error) {
	row := q.db.QueryRowContext(ctx, getBeam, id)
	var i Beam
	err := row.Scan(
		&i.ID,
		&i.BeamhallID,
		&i.Slug,
		&i.DisplayName,
		&i.RuntimeHint,
		&i.Mode,
		&i.State,
		&i.CurrentReleaseID,
		&i.DesiredReleaseID,
		&i.SecurityTemplate,
		&i.PreviewPauseAfter,
		&i.ResumedAt,
		&i.GitRemoteUrl,
		&i.RepoID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PreviewHost,
		&i.LiveReleaseID,
		&i.LiveState,
	)
	return i, err
}

const getBeamBySlug = `-- name: GetBeamBySlug :one
SELECT id, beamhall_id, slug, display_name, runtime_hint, mode, state, current_release_id, desired_release_id, security_template, preview_pause_after, resumed_at, git_remote_url, repo_id, created_by, created_at, updated_at, status, preview_host, live_release_id, live_state FROM beams WHERE beamhall_id = ? AND slug = ? AND status = 'active'
`

type GetBeamBySlugParams struct {
	BeamhallID string
	Slug       string
}

func (q *Queries) GetBeamBySlug(ctx context.Context, arg GetBeamBySlugParams) (Beam, error) {
	row := q.db.QueryRowContext(ctx, getBeamBySlug, arg.BeamhallID, arg.Slug)
	var i Beam
	err := row.Scan(
		&i.ID,
		&i.BeamhallID,
		&i.Slug,
		&i.DisplayName,
		&i.RuntimeHint,
		&i.Mode,
		&i.State,
		&i.CurrentReleaseID,
		&i.DesiredReleaseID,
		&i.SecurityTemplate,
		&i.PreviewPauseAfter,
		&i.ResumedAt,
		&i.GitRemoteUrl,
		&i.RepoID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.PreviewHost,
		&i.LiveReleaseID,
		&i.LiveState,
	)
	return i, err
}

const insertBeam = `-- name: InsertBeam :exec
INSERT INTO beams (
    id, beamhall_id, slug, display_name, runtime_hint, mode, state,
    current_release_id, desired_release_id, live_release_id, live_state,
    security_template, preview_pause_after, resumed_at, git_remote_url, repo_id,
    created_by, created_at, updated_at, status, preview_host
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBeamParams struct {
	ID                string
	BeamhallID        string
	Slug              string
	DisplayName       string
	RuntimeHint       string
	Mode              string
	State             string
	CurrentReleaseID  string
	DesiredReleaseID  string
	LiveReleaseID     string
	LiveState         string
	SecurityTemplate  string
	PreviewPauseAfter int64
	ResumedAt         int64
	GitRemoteUrl      string
	RepoID            string
	CreatedBy         string
	CreatedAt         int64
	UpdatedAt         int64
	Status            string
	PreviewHost       string
}

func (q *Queries) InsertBeam(ctx context.Context, arg InsertBeamParams) error {
	_, err := q.db.ExecContext(ctx, insertBeam,
		arg.ID,
		arg.BeamhallID,
		arg.Slug,
		arg.DisplayName,
		arg.RuntimeHint,
		arg.Mode,
		arg.State,
		arg.CurrentReleaseID,
		arg.DesiredReleaseID,
		arg.LiveReleaseID,
		arg.LiveState,
		arg.SecurityTemplate,
		arg.PreviewPauseAfter,
		arg.ResumedAt,
		arg.GitRemoteUrl,
		arg.RepoID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Status,
		arg.PreviewHost,
	)
	return err
}

const listBeamsByBeamhall = `-- name: ListBeamsByBeamhall :many
SELECT id, beamhall_id, slug, display_name, runtime_hint, mode, state, current_release_id, desired_release_id, security_template, preview_pause_after, resumed_at, git_remote_url, repo_id, created_by, created_at, updated_at, status, preview_host, live_release_id, live_state FROM beams WHERE beamhall_id = ? AND status = 'active' ORDER BY slug
`

func (q *Queries) ListBeamsByBeamhall(ctx context.Context, beamhallID string) ([]Beam, error) {
	rows, err := q.db.QueryContext(ctx, listBeamsByBeamhall, beamhallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Beam
	for rows.Next() {
		var i Beam
		if err := rows.Scan(
			&i.ID,
			&i.BeamhallID,
			&i.Slug,
			&i.DisplayName,
			&i.RuntimeHint,
			&i.Mode,
			&i.State,
			&i.CurrentReleaseID,
			&i.DesiredReleaseID,
			&i.SecurityTemplate,
			&i.PreviewPauseAfter,
			&i.ResumedAt,
			&i.GitRemoteUrl,
			&i.RepoID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.PreviewHost,
			&i.LiveReleaseID,
			&i.LiveState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteBeam = `-- name: PromoteBeam :execrows
UPDATE beams SET mode = 'live', updated_at = ? WHERE id = ?
`

type PromoteBeamParams struct {
	UpdatedAt int64
	ID        string
}

// Reserves a live slot by flipping mode to live in the same tx as the slot count.
// The preview channel's state is untouched; live_release_id/live_state are set
// by the orchestrator once the live workload is healthy.
func (q *Queries) PromoteBeam(ctx context.Context, arg PromoteBeamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promoteBeam, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateBeam = `-- name: UpdateBeam :execrows
UPDATE beams SET
    display_name = ?, runtime_hint = ?, mode = ?, state = ?,
    current_release_id = ?, desired_release_id = ?,
    live_release_id = ?, live_state = ?, security_template = ?,
    preview_pause_after = ?, resumed_at = ?, git_remote_url = ?, repo_id = ?,
    status = ?, updated_at = ?, preview_host = ?
WHERE id = ?
`

type UpdateBeamParams struct {
	DisplayName       string
	RuntimeHint       string
	Mode              string
	State             string
	CurrentReleaseID  string
	DesiredReleaseID  string
	LiveReleaseID     string
	LiveState         string
	SecurityTemplate  string
	PreviewPauseAfter int64
	ResumedAt         int64
	GitRemoteUrl      string
	RepoID            string
	Status            string
	UpdatedAt         int64
	PreviewHost       string
	ID                string
}

func (q *Queries) UpdateBeam(ctx context.Context, arg UpdateBeamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBeam,
		arg.DisplayName,
		arg.RuntimeHint,
		arg.Mode,
		arg.State,
		arg.CurrentReleaseID,
		arg.DesiredReleaseID,
		arg.LiveReleaseID,
		arg.LiveState,
		arg.SecurityTemplate,
		arg.PreviewPauseAfter,
		arg.ResumedAt,
		arg.GitRemoteUrl,
		arg.RepoID,
		arg.Status,
		arg.UpdatedAt,
		arg.PreviewHost,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
