// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beam_peers.sql

package db

import (
	"context"
)

const deleteBeamPeers = `-- name: DeleteBeamPeers :exec
DELETE FROM beam_peers WHERE source_beam_id = ?
`

func (q *Queries) DeleteBeamPeers(ctx context.Context, sourceBeamID string) error {
	_, err := q.db.ExecContext(ctx, deleteBeamPeers, sourceBeamID)
	return err
}

const getBeamPeers = `-- name: GetBeamPeers :one
SELECT source_beam_id, beamhall_id, peers_json, updated_by, updated_at FROM beam_peers WHERE source_beam_id = ?
`

func (q *Queries) GetBeamPeers(ctx context.Context, sourceBeamID string) (BeamPeer, error) {
	row := q.db.QueryRowContext(ctx, getBeamPeers, sourceBeamID)
	var i BeamPeer
	err := row.Scan(
		&i.SourceBeamID,
		&i.BeamhallID,
		&i.PeersJson,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listBeamPeers = `-- name: ListBeamPeers :many
SELECT source_beam_id, beamhall_id, peers_json, updated_by, updated_at FROM beam_peers ORDER BY source_beam_id
`

func (q *Queries) ListBeamPeers(ctx context.Context) ([]BeamPeer, error) {
	rows, err := q.db.QueryContext(ctx, listBeamPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BeamPeer
	for rows.Next() {
		var i BeamPeer
		if err := rows.Scan(
			&i.SourceBeamID,
			&i.BeamhallID,
			&i.PeersJson,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBeamPeers = `-- name: UpsertBeamPeers :exec
INSERT INTO beam_peers (source_beam_id, beamhall_id, peers_json, updated_by, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (source_beam_id) DO UPDATE SET
    peers_json = excluded.peers_json,
    updated_by = excluded.updated_by,
    updated_at = excluded.updated_at
`

type UpsertBeamPeersParams struct {
	SourceBeamID string
	BeamhallID   string
	PeersJson    string
	UpdatedBy    string
	UpdatedAt    int64
}

func (q *Queries) UpsertBeamPeers(ctx context.Context, arg UpsertBeamPeersParams) error {
	_, err := q.db.ExecContext(ctx, upsertBeamPeers,
		arg.SourceBeamID,
		arg.BeamhallID,
		arg.PeersJson,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
