// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beam_audiences.sql

package db

import (
	"context"
)

const deleteBeamAudience = `-- name: DeleteBeamAudience :exec
DELETE FROM beam_audiences WHERE beam_id = ?
`

func (q *Queries) DeleteBeamAudience(ctx context.Context, beamID string) error {
	_, err := q.db.ExecContext(ctx, deleteBeamAudience, beamID)
	return err
}

const getBeamAudience = `-- name: GetBeamAudience :one
SELECT beam_id, beamhall_id, audience_json, published_by, published_at, updated_at FROM beam_audiences WHERE beam_id = ?
`

func (q *Queries) GetBeamAudience(ctx context.Context, beamID string) (BeamAudience, error) {
	row := q.db.QueryRowContext(ctx, getBeamAudience, beamID)
	var i BeamAudience
	err := row.Scan(
		&i.BeamID,
		&i.BeamhallID,
		&i.AudienceJson,
		&i.PublishedBy,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBeamAudiences = `-- name: ListBeamAudiences :many
SELECT beam_id, beamhall_id, audience_json, published_by, published_at, updated_at FROM beam_audiences ORDER BY published_at
`

func (q *Queries) ListBeamAudiences(ctx context.Context) ([]BeamAudience, error) {
	rows, err := q.db.QueryContext(ctx, listBeamAudiences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BeamAudience
	for rows.Next() {
		var i BeamAudience
		if err := rows.Scan(
			&i.BeamID,
			&i.BeamhallID,
			&i.AudienceJson,
			&i.PublishedBy,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBeamAudiencesByBeamhall = `-- name: ListBeamAudiencesByBeamhall :many
SELECT beam_id, beamhall_id, audience_json, published_by, published_at, updated_at FROM beam_audiences WHERE beamhall_id = ? ORDER BY published_at
`

func (q *Queries) ListBeamAudiencesByBeamhall(ctx context.Context, beamhallID string) ([]BeamAudience, error) {
	rows, err := q.db.QueryContext(ctx, listBeamAudiencesByBeamhall, beamhallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BeamAudience
	for rows.Next() {
		var i BeamAudience
		if err := rows.Scan(
			&i.BeamID,
			&i.BeamhallID,
			&i.AudienceJson,
			&i.PublishedBy,
			&i.PublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBeamAudience = `-- name: UpsertBeamAudience :exec
INSERT INTO beam_audiences (beam_id, beamhall_id, audience_json, published_by, published_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (beam_id) DO UPDATE SET
    audience_json = excluded.audience_json,
    updated_at = excluded.updated_at
`

type UpsertBeamAudienceParams struct {
	BeamID       string
	BeamhallID   string
	AudienceJson string
	PublishedBy  string
	PublishedAt  int64
	UpdatedAt    int64
}

// published_by/published_at survive a re-publish: they record the first one.
func (q *Queries) UpsertBeamAudience(ctx context.Context, arg UpsertBeamAudienceParams) error {
	_, err := q.db.ExecContext(ctx, upsertBeamAudience,
		arg.BeamID,
		arg.BeamhallID,
		arg.AudienceJson,
		arg.PublishedBy,
		arg.PublishedAt,
		arg.UpdatedAt,
	)
	return err
}
