// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branding.sql

package db

import (
	"context"
)

const deleteBranding = `-- name: DeleteBranding :exec
DELETE FROM branding WHERE beamhall_id = ?
`

func (q *Queries) DeleteBranding(ctx context.Context, beamhallID string) error {
	_, err := q.db.ExecContext(ctx, deleteBranding, beamhallID)
	return err
}

const deleteBrandingLogo = `-- name: DeleteBrandingLogo :exec
DELETE FROM branding_logos WHERE beamhall_id = ?
`

func (q *Queries) DeleteBrandingLogo(ctx context.Context, beamhallID string) error {
	_, err := q.db.ExecContext(ctx, deleteBrandingLogo, beamhallID)
	return err
}

const getBranding = `-- name: GetBranding :one
SELECT beamhall_id, branding_json, updated_at FROM branding WHERE beamhall_id = ?
`

func (q *Queries) GetBranding(ctx context.Context, beamhallID string) (Branding, error) {
	row := q.db.QueryRowContext(ctx, getBranding, beamhallID)
	var i Branding
	err := row.Scan(&i.BeamhallID, &i.BrandingJson, &i.UpdatedAt)
	return i, err
}

const getBrandingLogo = `-- name: GetBrandingLogo :one
SELECT beamhall_id, logo, logo_mime, logo_etag, updated_at FROM branding_logos WHERE beamhall_id = ?
`

func (q *Queries) GetBrandingLogo(ctx context.Context, beamhallID string) (BrandingLogo, error) {
	row := q.db.QueryRowContext(ctx, getBrandingLogo, beamhallID)
	var i BrandingLogo
	err := row.Scan(
		&i.BeamhallID,
		&i.Logo,
		&i.LogoMime,
		&i.LogoEtag,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandingLogoMeta = `-- name: GetBrandingLogoMeta :one
SELECT beamhall_id, logo_mime, logo_etag, updated_at FROM branding_logos WHERE beamhall_id = ?
`

type GetBrandingLogoMetaRow struct {
	BeamhallID string
	LogoMime   string
	LogoEtag   string
	UpdatedAt  int64
}

func (q *Queries) GetBrandingLogoMeta(ctx context.Context, beamhallID string) (GetBrandingLogoMetaRow, error) {
	row := q.db.QueryRowContext(ctx, getBrandingLogoMeta, beamhallID)
	var i GetBrandingLogoMetaRow
	err := row.Scan(
		&i.BeamhallID,
		&i.LogoMime,
		&i.LogoEtag,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBranding = `-- name: UpsertBranding :exec
INSERT INTO branding (beamhall_id, branding_json, updated_at)
VALUES (?, ?, ?)
ON CONFLICT (beamhall_id) DO UPDATE SET
    branding_json = excluded.branding_json,
    updated_at = excluded.updated_at
`

type UpsertBrandingParams struct {
	BeamhallID   string
	BrandingJson string
	UpdatedAt    int64
}

func (q *Queries) UpsertBranding(ctx context.Context, arg UpsertBrandingParams) error {
	_, err := q.db.ExecContext(ctx, upsertBranding, arg.BeamhallID, arg.BrandingJson, arg.UpdatedAt)
	return err
}

const upsertBrandingLogo = `-- name: UpsertBrandingLogo :exec
INSERT INTO branding_logos (beamhall_id, logo, logo_mime, logo_etag, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (beamhall_id) DO UPDATE SET
    logo = excluded.logo,
    logo_mime = excluded.logo_mime,
    logo_etag = excluded.logo_etag,
    updated_at = excluded.updated_at
`

type UpsertBrandingLogoParams struct {
	BeamhallID string
	Logo       []byte
	LogoMime   string
	LogoEtag   string
	UpdatedAt  int64
}

func (q *Queries) UpsertBrandingLogo(ctx context.Context, arg UpsertBrandingLogoParams) error {
	_, err := q.db.ExecContext(ctx, upsertBrandingLogo,
		arg.BeamhallID,
		arg.Logo,
		arg.LogoMime,
		arg.LogoEtag,
		arg.UpdatedAt,
	)
	return err
}
