// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package db

import (
	"context"
)

const getBuild = `-- name: GetBuild :one
SELECT id, beam_id, source_ref, source_kind, builder, status, image_ref, image_digest, sbom_ref, cve_scan_status, log_stream_id, triggered_by, started_at, finished_at FROM builds WHERE id = ?
`

func (q *Queries) GetBuild(ctx context.Context, id string) (Build, error) {
	row := q.db.QueryRowContext(ctx, getBuild, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.BeamID,
		&i.SourceRef,
		&i.SourceKind,
		&i.Builder,
		&i.Status,
		&i.ImageRef,
		&i.ImageDigest,
		&i.SbomRef,
		&i.CveScanStatus,
		&i.LogStreamID,
		&i.TriggeredBy,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertBuild = `-- name: InsertBuild :exec
INSERT INTO builds (
    id, beam_id, source_ref, source_kind, builder, status, image_ref,
    image_digest, sbom_ref, cve_scan_status, log_stream_id, triggered_by,
    started_at, finished_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertBuildParams struct {
	ID            string
	BeamID        string
	SourceRef     string
	SourceKind    string
	Builder       string
	Status        string
	ImageRef      string
	ImageDigest   string
	SbomRef       string
	CveScanStatus string
	LogStreamID   string
	TriggeredBy   string
	StartedAt     int64
	FinishedAt    int64
}

func (q *Queries) InsertBuild(ctx context.Context, arg InsertBuildParams) error {
	_, err := q.db.ExecContext(ctx, insertBuild,
		arg.ID,
		arg.BeamID,
		arg.SourceRef,
		arg.SourceKind,
		arg.Builder,
		arg.Status,
		arg.ImageRef,
		arg.ImageDigest,
		arg.SbomRef,
		arg.CveScanStatus,
		arg.LogStreamID,
		arg.TriggeredBy,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const listBuildsByBeam = `-- name: ListBuildsByBeam :many
SELECT id, beam_id, source_ref, source_kind, builder, status, image_ref, image_digest, sbom_ref, cve_scan_status, log_stream_id, triggered_by, started_at, finished_at FROM builds WHERE beam_id = ? ORDER BY started_at DESC
`

func (q *Queries) ListBuildsByBeam(ctx context.Context, beamID string) ([]Build, error) {
	rows, err := q.db.QueryContext(ctx, listBuildsByBeam, beamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.BeamID,
			&i.SourceRef,
			&i.SourceKind,
			&i.Builder,
			&i.Status,
			&i.ImageRef,
			&i.ImageDigest,
			&i.SbomRef,
			&i.CveScanStatus,
			&i.LogStreamID,
			&i.TriggeredBy,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuild = `-- name: UpdateBuild :execrows
UPDATE builds SET
    status = ?, image_ref = ?, image_digest = ?, sbom_ref = ?,
    cve_scan_status = ?, log_stream_id = ?, finished_at = ?
WHERE id = ?
`

type UpdateBuildParams struct {
	Status        string
	ImageRef      string
	ImageDigest   string
	SbomRef       string
	CveScanStatus string
	LogStreamID   string
	FinishedAt    int64
	ID            string
}

func (q *Queries) UpdateBuild(ctx context.Context, arg UpdateBuildParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBuild,
		arg.Status,
		arg.ImageRef,
		arg.ImageDigest,
		arg.SbomRef,
		arg.CveScanStatus,
		arg.LogStreamID,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
