// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: c2c_keys.sql

package db

import (
	"context"
)

const deleteC2CKey = `-- name: DeleteC2CKey :exec
DELETE FROM c2c_keys WHERE beam_id = ?
`

func (q *Queries) DeleteC2CKey(ctx context.Context, beamID string) error {
	_, err := q.db.ExecContext(ctx, deleteC2CKey, beamID)
	return err
}

const getC2CKeyByBeam = `-- name: GetC2CKeyByBeam :one
SELECT beam_id, key_hash, created_at FROM c2c_keys WHERE beam_id = ?
`

func (q *Queries) GetC2CKeyByBeam(ctx context.Context, beamID string) (C2cKey, error) {
	row := q.db.QueryRowContext(ctx, getC2CKeyByBeam, beamID)
	var i C2cKey
	err := row.Scan(&i.BeamID, &i.KeyHash, &i.CreatedAt)
	return i, err
}

const getC2CKeyByHash = `-- name: GetC2CKeyByHash :one
SELECT beam_id, key_hash, created_at FROM c2c_keys WHERE key_hash = ?
`

func (q *Queries) GetC2CKeyByHash(ctx context.Context, keyHash string) (C2cKey, error) {
	row := q.db.QueryRowContext(ctx, getC2CKeyByHash, keyHash)
	var i C2cKey
	err := row.Scan(&i.BeamID, &i.KeyHash, &i.CreatedAt)
	return i, err
}

const insertC2CKey = `-- name: InsertC2CKey :execrows
INSERT INTO c2c_keys (beam_id, key_hash, created_at)
VALUES (?, ?, ?)
ON CONFLICT (beam_id) DO NOTHING
`

type InsertC2CKeyParams struct {
	BeamID    string
	KeyHash   string
	CreatedAt int64
}

// ON CONFLICT DO NOTHING makes the insert the mint mutex: exactly one of two
// racing mints proceeds to seal the key material.
func (q *Queries) InsertC2CKey(ctx context.Context, arg InsertC2CKeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertC2CKey, arg.BeamID, arg.KeyHash, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
