// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: control_keys.sql

package db

import (
	"context"
)

const getControlKey = `-- name: GetControlKey :one
SELECT kind, sealed, created_at FROM control_keys WHERE kind = ?
`

func (q *Queries) GetControlKey(ctx context.Context, kind string) (ControlKey, error) {
	row := q.db.QueryRowContext(ctx, getControlKey, kind)
	var i ControlKey
	err := row.Scan(&i.Kind, &i.Sealed, &i.CreatedAt)
	return i, err
}

const insertControlKey = `-- name: InsertControlKey :exec
INSERT INTO control_keys (kind, sealed, created_at) VALUES (?, ?, ?)
`

type InsertControlKeyParams struct {
	Kind      string
	Sealed    string
	CreatedAt int64
}

func (q *Queries) InsertControlKey(ctx context.Context, arg InsertControlKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertControlKey, arg.Kind, arg.Sealed, arg.CreatedAt)
	return err
}
