// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package db

import (
	"context"
)

const deleteIdentity = `-- name: DeleteIdentity :exec
DELETE FROM identities WHERE id = ?
`

func (q *Queries) DeleteIdentity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIdentity, id)
	return err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE id = ?
`

func (q *Queries) DeleteMembership(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMembership, id)
	return err
}

const getIdentity = `-- name: GetIdentity :one
SELECT id, external_subject, email, display_name, idp_issuer, status, created_at FROM identities WHERE id = ?
`

func (q *Queries) GetIdentity(ctx context.Context, id string) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentity, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.ExternalSubject,
		&i.Email,
		&i.DisplayName,
		&i.IdpIssuer,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByIssuerSubject = `-- name: GetIdentityByIssuerSubject :one
SELECT id, external_subject, email, display_name, idp_issuer, status, created_at FROM identities WHERE idp_issuer = ? AND external_subject = ?
`

type GetIdentityByIssuerSubjectParams struct {
	IdpIssuer       string
	ExternalSubject string
}

func (q *Queries) GetIdentityByIssuerSubject(ctx context.Context, arg GetIdentityByIssuerSubjectParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByIssuerSubject, arg.IdpIssuer, arg.ExternalSubject)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.ExternalSubject,
		&i.Email,
		&i.DisplayName,
		&i.IdpIssuer,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, identity_id, beamhall_id, role, granted_by, granted_at FROM memberships WHERE identity_id = ? AND beamhall_id = ?
`

type GetMembershipParams struct {
	IdentityID string
	BeamhallID string
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRowContext(ctx, getMembership, arg.IdentityID, arg.BeamhallID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.BeamhallID,
		&i.Role,
		&i.GrantedBy,
		&i.GrantedAt,
	)
	return i, err
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO identities (id, external_subject, email, display_name, idp_issuer, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertIdentityParams struct {
	ID              string
	ExternalSubject string
	Email           string
	DisplayName     string
	IdpIssuer       string
	Status          string
	CreatedAt       int64
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertIdentity,
		arg.ID,
		arg.ExternalSubject,
		arg.Email,
		arg.DisplayName,
		arg.IdpIssuer,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertMembership = `-- name: InsertMembership :exec
INSERT INTO memberships (id, identity_id, beamhall_id, role, granted_by, granted_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertMembershipParams struct {
	ID         string
	IdentityID string
	BeamhallID string
	Role       string
	GrantedBy  string
	GrantedAt  int64
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) error {
	_, err := q.db.ExecContext(ctx, insertMembership,
		arg.ID,
		arg.IdentityID,
		arg.BeamhallID,
		arg.Role,
		arg.GrantedBy,
		arg.GrantedAt,
	)
	return err
}

const listIdentities = `-- name: ListIdentities :many
SELECT id, external_subject, email, display_name, idp_issuer, status, created_at FROM identities ORDER BY email
`

func (q *Queries) ListIdentities(ctx context.Context) ([]Identity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.ExternalSubject,
			&i.Email,
			&i.DisplayName,
			&i.IdpIssuer,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByBeamhall = `-- name: ListMembershipsByBeamhall :many
SELECT id, identity_id, beamhall_id, role, granted_by, granted_at FROM memberships WHERE beamhall_id = ? ORDER BY granted_at
`

func (q *Queries) ListMembershipsByBeamhall(ctx context.Context, beamhallID string) ([]Membership, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsByBeamhall, beamhallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.BeamhallID,
			&i.Role,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByIdentity = `-- name: ListMembershipsByIdentity :many
SELECT id, identity_id, beamhall_id, role, granted_by, granted_at FROM memberships WHERE identity_id = ? ORDER BY granted_at
`

func (q *Queries) ListMembershipsByIdentity(ctx context.Context, identityID string) ([]Membership, error) {
	rows, err := q.db.QueryContext(ctx, listMembershipsByIdentity, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.BeamhallID,
			&i.Role,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIdentity = `-- name: UpdateIdentity :execrows
UPDATE identities SET email = ?, display_name = ?, status = ? WHERE id = ?
`

type UpdateIdentityParams struct {
	Email       string
	DisplayName string
	Status      string
	ID          string
}

func (q *Queries) UpdateIdentity(ctx context.Context, arg UpdateIdentityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateIdentity,
		arg.Email,
		arg.DisplayName,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
