// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type AdminActionRequest struct {
	ID            string
	ActionType    string
	Summary       string
	PayloadCipher []byte
	RequestedBy   string
	Status        string
	Reason        string
	Result        string
	CreatedAt     int64
	DecidedBy     string
	DecidedAt     int64
}

type ArmedPause struct {
	BeamID   string
	Deadline int64
}

type AuditCheckpoint struct {
	ID          int64
	ThroughSeq  int64
	AnchorHash  string
	PrunedCount int64
	At          int64
	PrunedBy    string
}

type AuditEvent struct {
	Seq           int64
	ID            string
	At            int64
	ActorID       string
	ActorTokenJti string
	BeamhallID    string
	BeamID        string
	Action        string
	Decision      string
	Reason        string
	RequestDigest string
	ResultStatus  string
	SourceIp      string
	PrevHash      string
	Hash          string
}

type Beam struct {
	ID                string
	BeamhallID        string
	Slug              string
	DisplayName       string
	RuntimeHint       string
	Mode              string
	State             string
	CurrentReleaseID  string
	DesiredReleaseID  string
	SecurityTemplate  string
	PreviewPauseAfter int64
	ResumedAt         int64
	GitRemoteUrl      string
	RepoID            string
	CreatedBy         string
	CreatedAt         int64
	UpdatedAt         int64
	Status            string
	PreviewHost       string
	LiveReleaseID     string
	LiveState         string
}

type Beamhall struct {
	ID                string
	Slug              string
	DisplayName       string
	Department        string
	Status            string
	SecurityContextID string
	NetworkPolicyJson string
	QuotaJson         string
	LiveSlotLimit     int64
	CreatedBy         string
	CreatedAt         int64
	UpdatedAt         int64
}

type Build struct {
	ID            string
	BeamID        string
	SourceRef     string
	SourceKind    string
	Builder       string
	Status        string
	ImageRef      string
	ImageDigest   string
	SbomRef       string
	CveScanStatus string
	LogStreamID   string
	TriggeredBy   string
	StartedAt     int64
	FinishedAt    int64
}

type Identity struct {
	ID              string
	ExternalSubject string
	Email           string
	DisplayName     string
	IdpIssuer       string
	Status          string
	CreatedAt       int64
}

type Membership struct {
	ID         string
	IdentityID string
	BeamhallID string
	Role       string
	GrantedBy  string
	GrantedAt  int64
}

type PromotionRequest struct {
	ID          string
	BeamhallID  string
	BeamID      string
	ReleaseID   string
	RequestedBy string
	Status      string
	Reason      string
	CreatedAt   int64
	DecidedBy   string
	DecidedAt   int64
}

type Release struct {
	ID                  string
	BeamID              string
	BuildID             string
	Version             int64
	ConfigSnapshotJson  string
	SecretRefsJson      string
	SecurityProfileJson string
	RouteID             string
	Status              string
	CreatedAt           int64
	ActivatedAt         int64
	HandleDriver        string
	HandleRef           string
	Channel             string
}

type Resource struct {
	ID                   string
	BeamhallID           string
	BeamID               string
	Type                 string
	Status               string
	ConnectionSecretJson string
	SpecJson             string
	BackingHandle        string
	CreatedAt            int64
	UpdatedAt            int64
	Channel              string
}

type Route struct {
	ID          string
	BeamID      string
	ReleaseID   string
	Kind        string
	Hostname    string
	RandomToken string
	BackendAddr string
	TlsCertRef  string
	Status      string
	CreatedAt   int64
	RetiredAt   int64
}

type Secret struct {
	ID         string
	BeamhallID string
	BeamID     string
	Key        string
	ValueRef   string
	Version    int64
	CreatedBy  string
	CreatedAt  int64
	Channel    string
}

type SecretValue struct {
	Ref        string
	Ciphertext []byte
	CreatedAt  int64
}

type SecurityContext struct {
	ID               string
	BeamhallID       string
	RuntimeClass     string
	UsernsRemap      bool
	CapDropJson      string
	CapAddJson       string
	SeccompProfile   string
	ApparmorProfile  string
	NoNewPrivileges  bool
	ReadOnlyRootfs   bool
	TmpfsJson        string
	CgroupLimitsJson string
	Template         string
}
