// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pauses.sql

package db

import (
	"context"
)

const deleteArmedPause = `-- name: DeleteArmedPause :exec
DELETE FROM armed_pauses WHERE beam_id = ?
`

func (q *Queries) DeleteArmedPause(ctx context.Context, beamID string) error {
	_, err := q.db.ExecContext(ctx, deleteArmedPause, beamID)
	return err
}

const listArmedPauses = `-- name: ListArmedPauses :many
SELECT beam_id, deadline FROM armed_pauses
`

func (q *Queries) ListArmedPauses(ctx context.Context) ([]ArmedPause, error) {
	rows, err := q.db.QueryContext(ctx, listArmedPauses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArmedPause
	for rows.Next() {
		var i ArmedPause
		if err := rows.Scan(&i.BeamID, &i.Deadline); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArmedPause = `-- name: UpsertArmedPause :exec
INSERT INTO armed_pauses (beam_id, deadline) VALUES (?, ?)
ON CONFLICT (beam_id) DO UPDATE SET deadline = excluded.deadline
`

type UpsertArmedPauseParams struct {
	BeamID   string
	Deadline int64
}

func (q *Queries) UpsertArmedPause(ctx context.Context, arg UpsertArmedPauseParams) error {
	_, err := q.db.ExecContext(ctx, upsertArmedPause, arg.BeamID, arg.Deadline)
	return err
}
