// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promotions.sql

package db

import (
	"context"
)

const decidePromotionRequest = `-- name: DecidePromotionRequest :execrows
UPDATE promotion_requests
SET status = ?, reason = ?, decided_by = ?, decided_at = ?
WHERE id = ? AND status = 'pending'
`

type DecidePromotionRequestParams struct {
	Status    string
	Reason    string
	DecidedBy string
	DecidedAt int64
	ID        string
}

func (q *Queries) DecidePromotionRequest(ctx context.Context, arg DecidePromotionRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decidePromotionRequest,
		arg.Status,
		arg.Reason,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPendingPromotionByBeam = `-- name: GetPendingPromotionByBeam :one
SELECT id, beamhall_id, beam_id, release_id, requested_by, status, reason, created_at, decided_by, decided_at FROM promotion_requests WHERE beam_id = ? AND status = 'pending'
`

func (q *Queries) GetPendingPromotionByBeam(ctx context.Context, beamID string) (PromotionRequest, error) {
	row := q.db.QueryRowContext(ctx, getPendingPromotionByBeam, beamID)
	var i PromotionRequest
	err := row.Scan(
		&i.ID,
		&i.BeamhallID,
		&i.BeamID,
		&i.ReleaseID,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const getPromotionRequest = `-- name: GetPromotionRequest :one
SELECT id, beamhall_id, beam_id, release_id, requested_by, status, reason, created_at, decided_by, decided_at FROM promotion_requests WHERE id = ?
`

func (q *Queries) GetPromotionRequest(ctx context.Context, id string) (PromotionRequest, error) {
	row := q.db.QueryRowContext(ctx, getPromotionRequest, id)
	var i PromotionRequest
	err := row.Scan(
		&i.ID,
		&i.BeamhallID,
		&i.BeamID,
		&i.ReleaseID,
		&i.RequestedBy,
		&i.Status,
		&i.Reason,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const insertPromotionRequest = `-- name: InsertPromotionRequest :exec
INSERT INTO promotion_requests (id, beamhall_id, beam_id, release_id, requested_by, status, created_at)
VALUES (?, ?, ?, ?, ?, 'pending', ?)
`

type InsertPromotionRequestParams struct {
	ID          string
	BeamhallID  string
	BeamID      string
	ReleaseID   string
	RequestedBy string
	CreatedAt   int64
}

func (q *Queries) InsertPromotionRequest(ctx context.Context, arg InsertPromotionRequestParams) error {
	_, err := q.db.ExecContext(ctx, insertPromotionRequest,
		arg.ID,
		arg.BeamhallID,
		arg.BeamID,
		arg.ReleaseID,
		arg.RequestedBy,
		arg.CreatedAt,
	)
	return err
}

const listPendingPromotionRequests = `-- name: ListPendingPromotionRequests :many
SELECT id, beamhall_id, beam_id, release_id, requested_by, status, reason, created_at, decided_by, decided_at FROM promotion_requests WHERE beamhall_id = ? AND status = 'pending' ORDER BY created_at
`

func (q *Queries) ListPendingPromotionRequests(ctx context.Context, beamhallID string) ([]PromotionRequest, error) {
	rows, err := q.db.QueryContext(ctx, listPendingPromotionRequests, beamhallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromotionRequest
	for rows.Next() {
		var i PromotionRequest
		if err := rows.Scan(
			&i.ID,
			&i.BeamhallID,
			&i.BeamID,
			&i.ReleaseID,
			&i.RequestedBy,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
