// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package db

import (
	"context"
)

const activateRelease = `-- name: ActivateRelease :execrows
UPDATE releases SET status = 'active', activated_at = ? WHERE id = ?
`

type ActivateReleaseParams struct {
	ActivatedAt int64
	ID          string
}

func (q *Queries) ActivateRelease(ctx context.Context, arg ActivateReleaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateRelease, arg.ActivatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRelease = `-- name: GetRelease :one
SELECT id, beam_id, build_id, version, config_snapshot_json, secret_refs_json, security_profile_json, route_id, status, created_at, activated_at, handle_driver, handle_ref, channel FROM releases WHERE id = ?
`

func (q *Queries) GetRelease(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.BeamID,
		&i.BuildID,
		&i.Version,
		&i.ConfigSnapshotJson,
		&i.SecretRefsJson,
		&i.SecurityProfileJson,
		&i.RouteID,
		&i.Status,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.HandleDriver,
		&i.HandleRef,
		&i.Channel,
	)
	return i, err
}

const insertRelease = `-- name: InsertRelease :exec
INSERT INTO releases (
    id, beam_id, build_id, version, channel, config_snapshot_json, secret_refs_json,
    security_profile_json, route_id, status, created_at, activated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertReleaseParams struct {
	ID                  string
	BeamID              string
	BuildID             string
	Version             int64
	Channel             string
	ConfigSnapshotJson  string
	SecretRefsJson      string
	SecurityProfileJson string
	RouteID             string
	Status              string
	CreatedAt           int64
	ActivatedAt         int64
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) error {
	_, err := q.db.ExecContext(ctx, insertRelease,
		arg.ID,
		arg.BeamID,
		arg.BuildID,
		arg.Version,
		arg.Channel,
		arg.ConfigSnapshotJson,
		arg.SecretRefsJson,
		arg.SecurityProfileJson,
		arg.RouteID,
		arg.Status,
		arg.CreatedAt,
		arg.ActivatedAt,
	)
	return err
}

const listReleasesByBeam = `-- name: ListReleasesByBeam :many
SELECT id, beam_id, build_id, version, config_snapshot_json, secret_refs_json, security_profile_json, route_id, status, created_at, activated_at, handle_driver, handle_ref, channel FROM releases WHERE beam_id = ? ORDER BY version DESC
`

func (q *Queries) ListReleasesByBeam(ctx context.Context, beamID string) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listReleasesByBeam, beamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.BeamID,
			&i.BuildID,
			&i.Version,
			&i.ConfigSnapshotJson,
			&i.SecretRefsJson,
			&i.SecurityProfileJson,
			&i.RouteID,
			&i.Status,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.HandleDriver,
			&i.HandleRef,
			&i.Channel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextReleaseVersion = `-- name: NextReleaseVersion :one
SELECT COALESCE(MAX(version), 0) + 1 FROM releases WHERE beam_id = ?
`

func (q *Queries) NextReleaseVersion(ctx context.Context, beamID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextReleaseVersion, beamID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setReleaseRoute = `-- name: SetReleaseRoute :execrows
UPDATE releases SET route_id = ? WHERE id = ?
`

type SetReleaseRouteParams struct {
	RouteID string
	ID      string
}

func (q *Queries) SetReleaseRoute(ctx context.Context, arg SetReleaseRouteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setReleaseRoute, arg.RouteID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setReleaseWorkload = `-- name: SetReleaseWorkload :execrows
UPDATE releases SET handle_driver = ?, handle_ref = ? WHERE id = ?
`

type SetReleaseWorkloadParams struct {
	HandleDriver string
	HandleRef    string
	ID           string
}

func (q *Queries) SetReleaseWorkload(ctx context.Context, arg SetReleaseWorkloadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setReleaseWorkload, arg.HandleDriver, arg.HandleRef, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateReleaseStatus = `-- name: UpdateReleaseStatus :execrows
UPDATE releases SET status = ? WHERE id = ?
`

type UpdateReleaseStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateReleaseStatus(ctx context.Context, arg UpdateReleaseStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateReleaseStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
