// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"
)

const countResourcesByBeamhallAndType = `-- name: CountResourcesByBeamhallAndType :one
SELECT COUNT(*) FROM resources WHERE beamhall_id = ? AND type = ? AND channel <> 'live'
`

type CountResourcesByBeamhallAndTypeParams struct {
	BeamhallID string
	Type       string
}

// Counts LOGICAL resources against quota: the live channel's mirror database is
// a consequence of promote (bounded by the preview count), not a new logical
// resource, so it does not additionally count toward MaxDBCount.
func (q *Queries) CountResourcesByBeamhallAndType(ctx context.Context, arg CountResourcesByBeamhallAndTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResourcesByBeamhallAndType, arg.BeamhallID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, beamhall_id, beam_id, type, status, connection_secret_json, spec_json, backing_handle, created_at, updated_at, channel FROM resources WHERE id = ?
`

func (q *Queries) GetResource(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.BeamhallID,
		&i.BeamID,
		&i.Type,
		&i.Status,
		&i.ConnectionSecretJson,
		&i.SpecJson,
		&i.BackingHandle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Channel,
	)
	return i, err
}

const insertResource = `-- name: InsertResource :exec
INSERT INTO resources (
    id, beamhall_id, beam_id, channel, type, status, connection_secret_json,
    spec_json, backing_handle, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertResourceParams struct {
	ID                   string
	BeamhallID           string
	BeamID               string
	Channel              string
	Type                 string
	Status               string
	ConnectionSecretJson string
	SpecJson             string
	BackingHandle        string
	CreatedAt            int64
	UpdatedAt            int64
}

func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) error {
	_, err := q.db.ExecContext(ctx, insertResource,
		arg.ID,
		arg.BeamhallID,
		arg.BeamID,
		arg.Channel,
		arg.Type,
		arg.Status,
		arg.ConnectionSecretJson,
		arg.SpecJson,
		arg.BackingHandle,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listResourcesByBeam = `-- name: ListResourcesByBeam :many
SELECT id, beamhall_id, beam_id, type, status, connection_secret_json, spec_json, backing_handle, created_at, updated_at, channel FROM resources WHERE beam_id = ? ORDER BY created_at
`

func (q *Queries) ListResourcesByBeam(ctx context.Context, beamID string) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByBeam, beamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.BeamhallID,
			&i.BeamID,
			&i.Type,
			&i.Status,
			&i.ConnectionSecretJson,
			&i.SpecJson,
			&i.BackingHandle,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Channel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByBeamAndChannel = `-- name: ListResourcesByBeamAndChannel :many
SELECT id, beamhall_id, beam_id, type, status, connection_secret_json, spec_json, backing_handle, created_at, updated_at, channel FROM resources WHERE beam_id = ? AND channel = ? ORDER BY created_at
`

type ListResourcesByBeamAndChannelParams struct {
	BeamID  string
	Channel string
}

func (q *Queries) ListResourcesByBeamAndChannel(ctx context.Context, arg ListResourcesByBeamAndChannelParams) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByBeamAndChannel, arg.BeamID, arg.Channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.BeamhallID,
			&i.BeamID,
			&i.Type,
			&i.Status,
			&i.ConnectionSecretJson,
			&i.SpecJson,
			&i.BackingHandle,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Channel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByBeamhall = `-- name: ListResourcesByBeamhall :many
SELECT id, beamhall_id, beam_id, type, status, connection_secret_json, spec_json, backing_handle, created_at, updated_at, channel FROM resources WHERE beamhall_id = ? ORDER BY created_at
`

func (q *Queries) ListResourcesByBeamhall(ctx context.Context, beamhallID string) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByBeamhall, beamhallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.BeamhallID,
			&i.BeamID,
			&i.Type,
			&i.Status,
			&i.ConnectionSecretJson,
			&i.SpecJson,
			&i.BackingHandle,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Channel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :execrows
UPDATE resources SET
    status = ?, connection_secret_json = ?, spec_json = ?, backing_handle = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateResourceParams struct {
	Status               string
	ConnectionSecretJson string
	SpecJson             string
	BackingHandle        string
	UpdatedAt            int64
	ID                   string
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateResource,
		arg.Status,
		arg.ConnectionSecretJson,
		arg.SpecJson,
		arg.BackingHandle,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
