// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"
)

const getActiveRouteByHostname = `-- name: GetActiveRouteByHostname :one
SELECT id, beam_id, release_id, kind, hostname, random_token, backend_addr, tls_cert_ref, status, created_at, retired_at FROM routes WHERE hostname = ? AND status = 'active'
`

func (q *Queries) GetActiveRouteByHostname(ctx context.Context, hostname string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getActiveRouteByHostname, hostname)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.BeamID,
		&i.ReleaseID,
		&i.Kind,
		&i.Hostname,
		&i.RandomToken,
		&i.BackendAddr,
		&i.TlsCertRef,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT id, beam_id, release_id, kind, hostname, random_token, backend_addr, tls_cert_ref, status, created_at, retired_at FROM routes WHERE id = ?
`

func (q *Queries) GetRoute(ctx context.Context, id string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.BeamID,
		&i.ReleaseID,
		&i.Kind,
		&i.Hostname,
		&i.RandomToken,
		&i.BackendAddr,
		&i.TlsCertRef,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const insertRoute = `-- name: InsertRoute :exec
INSERT INTO routes (
    id, beam_id, release_id, kind, hostname, random_token, backend_addr,
    tls_cert_ref, status, created_at, retired_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRouteParams struct {
	ID          string
	BeamID      string
	ReleaseID   string
	Kind        string
	Hostname    string
	RandomToken string
	BackendAddr string
	TlsCertRef  string
	Status      string
	CreatedAt   int64
	RetiredAt   int64
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) error {
	_, err := q.db.ExecContext(ctx, insertRoute,
		arg.ID,
		arg.BeamID,
		arg.ReleaseID,
		arg.Kind,
		arg.Hostname,
		arg.RandomToken,
		arg.BackendAddr,
		arg.TlsCertRef,
		arg.Status,
		arg.CreatedAt,
		arg.RetiredAt,
	)
	return err
}

const listActiveRoutes = `-- name: ListActiveRoutes :many
SELECT id, beam_id, release_id, kind, hostname, random_token, backend_addr, tls_cert_ref, status, created_at, retired_at FROM routes WHERE status = 'active' ORDER BY hostname
`

func (q *Queries) ListActiveRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.BeamID,
			&i.ReleaseID,
			&i.Kind,
			&i.Hostname,
			&i.RandomToken,
			&i.BackendAddr,
			&i.TlsCertRef,
			&i.Status,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByBeam = `-- name: ListRoutesByBeam :many
SELECT id, beam_id, release_id, kind, hostname, random_token, backend_addr, tls_cert_ref, status, created_at, retired_at FROM routes WHERE beam_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListRoutesByBeam(ctx context.Context, beamID string) ([]Route, error) {
	rows, err := q.db.QueryContext(ctx, listRoutesByBeam, beamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.BeamID,
			&i.ReleaseID,
			&i.Kind,
			&i.Hostname,
			&i.RandomToken,
			&i.BackendAddr,
			&i.TlsCertRef,
			&i.Status,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireRoute = `-- name: RetireRoute :execrows
UPDATE routes SET status = 'retired', retired_at = ? WHERE id = ?
`

type RetireRouteParams struct {
	RetiredAt int64
	ID        string
}

func (q *Queries) RetireRoute(ctx context.Context, arg RetireRouteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retireRoute, arg.RetiredAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
