// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_values.sql

package db

import (
	"context"
)

const deleteSecretValue = `-- name: DeleteSecretValue :exec
DELETE FROM secret_values WHERE ref = ?
`

func (q *Queries) DeleteSecretValue(ctx context.Context, ref string) error {
	_, err := q.db.ExecContext(ctx, deleteSecretValue, ref)
	return err
}

const getSecretValue = `-- name: GetSecretValue :one
SELECT ciphertext FROM secret_values WHERE ref = ?
`

func (q *Queries) GetSecretValue(ctx context.Context, ref string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSecretValue, ref)
	var ciphertext []byte
	err := row.Scan(&ciphertext)
	return ciphertext, err
}

const putSecretValue = `-- name: PutSecretValue :exec
INSERT INTO secret_values (ref, ciphertext, created_at) VALUES (?, ?, ?)
`

type PutSecretValueParams struct {
	Ref        string
	Ciphertext []byte
	CreatedAt  int64
}

func (q *Queries) PutSecretValue(ctx context.Context, arg PutSecretValueParams) error {
	_, err := q.db.ExecContext(ctx, putSecretValue, arg.Ref, arg.Ciphertext, arg.CreatedAt)
	return err
}
