// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"
)

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets WHERE beamhall_id = ? AND beam_id = ? AND key = ? AND channel = ?
`

type DeleteSecretParams struct {
	BeamhallID string
	BeamID     string
	Key        string
	Channel    string
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteSecret,
		arg.BeamhallID,
		arg.BeamID,
		arg.Key,
		arg.Channel,
	)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT id, beamhall_id, beam_id, "key", value_ref, version, created_by, created_at, channel FROM secrets WHERE beamhall_id = ? AND beam_id = ? AND key = ? AND channel = ?
`

type GetSecretParams struct {
	BeamhallID string
	BeamID     string
	Key        string
	Channel    string
}

func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecret,
		arg.BeamhallID,
		arg.BeamID,
		arg.Key,
		arg.Channel,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.BeamhallID,
		&i.BeamID,
		&i.Key,
		&i.ValueRef,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Channel,
	)
	return i, err
}

const listSecretsByBeamhall = `-- name: ListSecretsByBeamhall :many
SELECT id, beamhall_id, beam_id, "key", value_ref, version, created_by, created_at, channel FROM secrets WHERE beamhall_id = ? ORDER BY beam_id, key, channel
`

func (q *Queries) ListSecretsByBeamhall(ctx context.Context, beamhallID string) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecretsByBeamhall, beamhallID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.BeamhallID,
			&i.BeamID,
			&i.Key,
			&i.ValueRef,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Channel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSecret = `-- name: UpsertSecret :one
INSERT INTO secrets (id, beamhall_id, beam_id, key, channel, value_ref, version, created_by, created_at)
VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?)
ON CONFLICT (beamhall_id, beam_id, key, channel) DO UPDATE SET
    value_ref  = excluded.value_ref,
    version    = secrets.version + 1,
    created_by = excluded.created_by,
    created_at = excluded.created_at
RETURNING id, beamhall_id, beam_id, "key", value_ref, version, created_by, created_at, channel
`

type UpsertSecretParams struct {
	ID         string
	BeamhallID string
	BeamID     string
	Key        string
	Channel    string
	ValueRef   string
	CreatedBy  string
	CreatedAt  int64
}

func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, upsertSecret,
		arg.ID,
		arg.BeamhallID,
		arg.BeamID,
		arg.Key,
		arg.Channel,
		arg.ValueRef,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.BeamhallID,
		&i.BeamID,
		&i.Key,
		&i.ValueRef,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Channel,
	)
	return i, err
}
